default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: orange_development
  username: postgres
  password: postgres
  host: localhost
  port: 5432

test:
  <<: *default
  database: orange_test

production:
  <<: *default
  database: orange_production
  username: orange
  password: <%= ENV['ORANGE_DATABASE_PASSWORD'] %>
